alter session set nls_date_format = 'DD-MON-YYYY HH24:MI:SS';
SET LINE 500 PAGES 5000;
SET COLSEP ' | '
COL INPUT FORMAT A10
COL OUTPUT FORMAT A10
COL INPUT_SEC FORMAT A10
COL OUTPUT_SEC FORMAT A10
COL DB_NAME FORMAT A15
COL STATUS FORMAT A30
SELECT /*csv*/ sys_context('USERENV', 'DB_NAME') DB_NAME,
START_TIME as "DATE",
END_TIME,
TRIM('.' FROM TRIM(BOTH '0' FROM TRIM('+' FROM TO_CHAR(NUMTODSINTERVAL(elapsed_seconds, 'SECOND'), 'HH24:MI:SS')))) EXEC_TIME,
INPUT_TYPE,
--INPUT_BYTES_DISPLAY INPUT,
OUTPUT_BYTES_DISPLAY OUTPUT,
INPUT_BYTES_PER_SEC_DISPLAY INPUT_SEC,
OUTPUT_BYTES_PER_SEC_DISPLAY OUTPUT_SEC,
STATUS
FROM v$rman_backup_job_details
WHERE TRUNC(END_TIME) BETWEEN TRUNC(SYSDATE-100) 
AND TRUNC(SYSDATE) 
--AND STATUS<>'FAILED'
ORDER BY 2;