col SIZE_MB for 9999,999,999
set pages 500
col time for a50
PROMPT ARCHIVELOG SIZE EACH HOUR

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI';

select 
  THREAD#,trunc(COMPLETION_TIME,'HH24') TIME, 
   SUM(BLOCKS * BLOCK_SIZE)/1024/1024 SIZE_MB,count(SEQUENCE#) 
from 
  V$ARCHIVED_LOG 
group by 
  THREAD#,trunc (COMPLETION_TIME,'HH24') order by TIME;
  