PROMPT ARCHIVELOG SIZE EACH DAY

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI';

COL SIZE_MB FOR 9999,999,999

SELECT 
  THREAD#,TRUNC(COMPLETION_TIME) TIME, 
  SUM(BLOCKS * BLOCK_SIZE)/1024/1024 SIZE_MB,count(SEQUENCE#) 
FROM 
  V$ARCHIVED_LOG 
GROUP BY 
THREAD#,TRUNC (COMPLETION_TIME) ORDER BY 1;




