--Informa indices maiores que as tabelas (possivel problema)

COL TABLE FORMAT A30
COL INDEX FORMAT A30
SELECT T.OWNER, T.SEGMENT_NAME "TABLE", T.MEGAS "TABLE Mb", I.SEGMENT_NAME "INDEX", I.MEGAS "INDEX Mb"
FROM 
(
SELECT OWNER, SEGMENT_NAME, BYTES/1024/1024 MEGAS
FROM DBA_SEGMENTS
WHERE SEGMENT_TYPE = 'TABLE'
AND   OWNER NOT IN ('SYSMAN','PERFSTAT','DBSNMP','WKSYS','TRCANLZR','MDSYS','ORDSYS','OUTLN','WMSYS','XDB', 'WSM', 'CTXSYS', 'PUBLIC', 'SYS', 'SYSTEM', 'DMSYS', 'OLAPSYS')
AND   BYTES/1024/1024 > 1
) T
,
(
SELECT OWNER, SEGMENT_NAME, BYTES/1024/1024 MEGAS
FROM DBA_SEGMENTS
WHERE SEGMENT_TYPE = 'INDEX'
AND   OWNER NOT IN ('SYSMAN','PERFSTAT','DBSNMP','WKSYS','TRCANLZR','MDSYS','ORDSYS','OUTLN','WMSYS','XDB', 'WSM', 'CTXSYS', 'PUBLIC', 'SYS', 'SYSTEM', 'DMSYS', 'OLAPSYS')
AND   BYTES/1024/1024 > 1
) I
WHERE T.OWNER = I.OWNER
AND   I.SEGMENT_NAME IN (SELECT INDEX_NAME FROM DBA_INDEXES WHERE OWNER=I.OWNER AND TABLE_NAME = T.SEGMENT_NAME)
AND   I.MEGAS >= T.MEGAS*0.90  --- indice maior ou igual a 90% do tamanho da tabela.
ORDER BY 1,2
;
