-- Start of DDL Script for Sequence CTAS_CHANGE_BACKUP.SEQ_LIST_ID
-- Generated 6/2/2009 13:57:09 from CTAS_CHANGE_BACKUP@DEV

CREATE SEQUENCE CTAS_CHANGE_BACKUP.seq_list_id
  INCREMENT BY 1
  START WITH 141
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/

-- Grants for Sequence
GRANT SELECT ON CTAS_CHANGE_BACKUP.seq_list_id TO ctas_change_backup
/

-- End of DDL Script for Sequence CTAS_CHANGE_BACKUP.SEQ_LIST_ID



-- Start of DDL Script for Sequence CTAS_CHANGE_BACKUP.SEQ_LOG_ID
-- Generated 6/2/2009 13:57:32 from CTAS_CHANGE_BACKUP@DEV

CREATE SEQUENCE CTAS_CHANGE_BACKUP.seq_log_id
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/

-- Grants for Sequence
GRANT SELECT ON CTAS_CHANGE_BACKUP.seq_log_id TO ctas_change_backup
/

-- End of DDL Script for Sequence CTAS_CHANGE_BACKUP.CTAS_CHANGE_BACKUP.SEQ_LOG_ID
