SET LINESIZE 200
SET PAGESIZE 100
SET HEADING ON
COLUMN USERNAME FORMAT A30
COLUMN LAST_LOGIN FORMAT A20
COLUMN LOCK_DATE FORMAT A20
COLUMN ROLES FORMAT A100

-- Ajuste a lista de OWNERs para excluir os usuários desejados
WITH USER_ROLES AS (
    SELECT 
        GRANTEE AS USERNAME,
        GRANTED_ROLE
    FROM DBA_ROLE_PRIVS
),
USER_LAST_LOGIN AS (
    SELECT 
        USERNAME,
        MAX(TIMESTAMP) AS LAST_LOGIN
    FROM DBA_AUDIT_TRAIL
    WHERE ACTION_NAME = 'LOGON' -- Filtro para capturar apenas logons
    GROUP BY USERNAME
),
USER_INFO AS (
    SELECT 
        U.USERNAME,
        COALESCE(TO_CHAR(L.LAST_LOGIN, 'YYYY-MM-DD HH24:MI:SS'), 'NEVER') AS LAST_LOGIN,
        COALESCE(TO_CHAR(U.LOCK_DATE, 'YYYY-MM-DD HH24:MI:SS'), 'UNLOCKED') AS LOCK_DATE
    FROM DBA_USERS U
    LEFT JOIN USER_LAST_LOGIN L
    ON U.USERNAME = L.USERNAME
    WHERE U.ACCOUNT_STATUS = 'OPEN'
    AND U.USERNAME NOT IN ('ANONYMOUS','APEX_040200','APEX_PUBLIC_USER','APPQOSSYS','AUDSYS','CTXSYS','DBSNMP','DIP','DVF','DVSYS','EXFSYS','FLOWS_FILES','GSMADMIN_INTERNAL','GSMCATUSER','GSMUSER','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','ORACLE_OCM','ORDDATA','ORDSYS','ORDPLUGINS','OUTLN','SI_INFORMTN_SCHEMA','SCOTT','SYS','SYSDG','SYSKM','SYSMAN','SYSTEM','SYSBACKUP','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','WKPROXY','WKSYS','WK_TEST','WMSYS','XDB','XS$NULL','REMOTE_SCHEDULER_AGENT','APEX_030200',
'APEX_050000','ADMALOC','ADMBIP','ADMMSF','ADMOBI01','ADMRMS','ADMRMSETL','ADMRWMS','ADMSIM','ADMSP','ADMUHC','ADMWEBUTIL','ADVAULT','ANONYMOUS','APEX_PUBLIC_USER','APEX_030200','APPQOSSYS','BASELINE','BOOK_ORACLE','CTXSYS','DBSNMP','DIP','EXFSYS','FLOWS_FILES','MDDATA','MDSYS','MGMT_VIEW','OLAPSYS','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OUTLN','OWBSYS','OWBSYS_AUDIT','RMAN_CATPROD','RMAN_RTPRBR70','SERV_ALLOC_ZABBIX','SERV_RMS_ZABBIX','SERV_ZABBIX','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','SYS','SYSMAN','SYSTEM','UALLOC01','UALOC01','UBATCH01','UBIP01','UCAUIM01','UMONITOR','UOIM01','UPROD01','URAD01','URMS_ALLOC','URMS_CADASTRO','URMSCARGATRAVA','URMSESTOQUEAVARIA','URMS_MONITOR','URMS_PRECO','URMS01','URMS02','URMS03','URPM01','URWMS01','USIM01','USIVBATCH','USR_CCORP','USR_LOGIC','UTBL01','UTKP01','UXSTORE01','WMSYS','XDB','XS$NULL') 
-- Substitua pelos OWNERs a serem excluídos
)
SELECT 
    U.USERNAME,
    U.LAST_LOGIN,
    U.LOCK_DATE,
    LISTAGG(R.GRANTED_ROLE, ', ') WITHIN GROUP (ORDER BY R.GRANTED_ROLE) AS ROLES
FROM USER_INFO U
LEFT JOIN USER_ROLES R
ON U.USERNAME = R.USERNAME
GROUP BY U.USERNAME, U.LAST_LOGIN, U.LOCK_DATE
ORDER BY U.USERNAME;
