SET PAGESIZE 200
SET LINESIZE 200
COLUMN USERNAME FORMAT A20
COLUMN ACCOUNT_STATUS FORMAT A20
COLUMN CREATED FORMAT A30
COLUMN LAST_LOGIN FORMAT A30
COLUMN ORACLE_MAINTAINED FORMAT A20

WITH USER_LOGINS AS (
    SELECT 
        U.USERNAME,
        U.ACCOUNT_STATUS,
        TO_CHAR(U.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED,
        -- Obter o último login do usuário baseado em DBA_AUDIT_TRAIL (se auditoria estiver habilitada)
        NVL(TO_CHAR(MAX(A.TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS'), 'NEVER LOGGED IN') AS LAST_LOGIN
    FROM DBA_USERS U
    LEFT JOIN DBA_AUDIT_TRAIL A ON U.USERNAME = A.USERNAME
    GROUP BY U.USERNAME, U.ACCOUNT_STATUS, U.CREATED
),
FILTERED_USERS AS (
    SELECT 'ANONYMOUS' AS OWNER FROM DUAL UNION ALL
    SELECT 'APEX_040200' FROM DUAL UNION ALL
    SELECT 'APEX_PUBLIC_USER' FROM DUAL UNION ALL
    SELECT 'APPQOSSYS' FROM DUAL UNION ALL
    SELECT 'AUDSYS' FROM DUAL UNION ALL
    SELECT 'BI' FROM DUAL UNION ALL
    SELECT 'CTXSYS' FROM DUAL UNION ALL
    SELECT 'DBSNMP' FROM DUAL UNION ALL
    SELECT 'DIP' FROM DUAL UNION ALL
    SELECT 'DVF' FROM DUAL UNION ALL
    SELECT 'DVSYS' FROM DUAL UNION ALL
    SELECT 'EXFSYS' FROM DUAL UNION ALL
    SELECT 'FLOWS_FILES' FROM DUAL UNION ALL
    SELECT 'GSMADMIN_INTERNAL' FROM DUAL UNION ALL
    SELECT 'GSMCATUSER' FROM DUAL UNION ALL
    SELECT 'GSMUSER' FROM DUAL UNION ALL
    SELECT 'HR' FROM DUAL UNION ALL
    SELECT 'IX' FROM DUAL UNION ALL
    SELECT 'LBACSYS' FROM DUAL UNION ALL
    SELECT 'MDDATA' FROM DUAL UNION ALL
    SELECT 'MDSYS' FROM DUAL UNION ALL
    SELECT 'OE' FROM DUAL UNION ALL
    SELECT 'ORACLE_OCM' FROM DUAL UNION ALL
    SELECT 'ORDDATA' FROM DUAL UNION ALL
    SELECT 'ORDPLUGINS' FROM DUAL UNION ALL
    SELECT 'ORDSYS' FROM DUAL UNION ALL
    SELECT 'OUTLN' FROM DUAL UNION ALL
    SELECT 'PM' FROM DUAL UNION ALL
    SELECT 'SCOTT' FROM DUAL UNION ALL
    SELECT 'SH' FROM DUAL UNION ALL
    SELECT 'SI_INFORMTN_SCHEMA' FROM DUAL UNION ALL
    SELECT 'SPATIAL_CSW_ADMIN_USR' FROM DUAL UNION ALL
    SELECT 'SPATIAL_WFS_ADMIN_USR' FROM DUAL UNION ALL
    SELECT 'SYS' FROM DUAL UNION ALL
    SELECT 'SYSBACKUP' FROM DUAL UNION ALL
    SELECT 'SYSDG' FROM DUAL UNION ALL
    SELECT 'SYSKM' FROM DUAL UNION ALL
    SELECT 'SYSTEM' FROM DUAL UNION ALL
    SELECT 'WMSYS' FROM DUAL UNION ALL
    SELECT 'XDB' FROM DUAL UNION ALL
    SELECT 'SYSMAN' FROM DUAL UNION ALL
    SELECT 'OWBSYS' FROM DUAL UNION ALL
    SELECT 'OWBSYS_AUDIT' FROM DUAL UNION ALL
    SELECT 'APEX_030200' FROM DUAL UNION ALL
    SELECT 'MGMT_VIEW' FROM DUAL UNION ALL
    SELECT 'XS$NULL' FROM DUAL UNION ALL
    SELECT 'SYSRAC' FROM DUAL UNION ALL
    SELECT 'SYS$UMF' FROM DUAL UNION ALL
    SELECT 'REMOTE_SCHEDULER_AGENT' FROM DUAL UNION ALL
    SELECT 'OLAPSYS' FROM DUAL UNION ALL
    SELECT 'GGSYS' FROM DUAL UNION ALL
    SELECT 'DBSFWUSER' FROM DUAL UNION ALL
    SELECT 'APEX_180200' FROM DUAL UNION ALL
    SELECT 'APEX_INSTANCE_ADMIN_USER' FROM DUAL UNION ALL
    SELECT 'OJVMSYS' FROM DUAL
)
SELECT 
    UL.USERNAME,
    UL.ACCOUNT_STATUS,
    UL.CREATED,
    UL.LAST_LOGIN,
    CASE 
        WHEN UL.USERNAME IN (SELECT OWNER FROM FILTERED_USERS) THEN 'Y'
        ELSE 'N'
    END AS ORACLE_MAINTAINED
FROM USER_LOGINS UL
ORDER BY UL.USERNAME;