
-- staggered_sequence_trigger.sql

CREATE TRIGGER insert_EMP_PK
BEFORE insert ON EMP
FOR EACH ROW
DECLARE
INST_ID NUMBER;
SEQ_NUM NUMBER;
INST_SEQ_ID NUMBER;
BEGIN
select
    INSTANCE_NUMBER INTO INST_ID
  FROM
    V$INSTANCE;
  select
    EMP_ID_SEQ.NEXTVAL INTO SEQ_NUM
  FROM
    DUAL;
  INST_SEQ_ID:=(INST_ID-1)*100000 + SEQ_NUM;
  :NEW.EMP_ID:=INST_SEQ_ID;
END;.
