CREATE PROFILE GLOGIN_APPL LIMIT
   PASSWORD_LIFE_TIME UNLIMITED
   PASSWORD_GRACE_TIME UNLIMITED
   PASSWORD_REUSE_TIME UNLIMITED
   PASSWORD_REUSE_MAX UNLIMITED
   PASSWORD_VERIFY_FUNCTION VERIFY_FUN_GLOGIN
   FAILED_LOGIN_ATTEMPTS 15
   PASSWORD_LOCK_TIME UNLIMITED;