SELECT 
    aud.os_user,
    aud.host_name,
    aud.client_program_name,
    aud.event_timestamp,
    CASE 
        WHEN aud.action = act.action THEN act.name
        ELSE 'Desconhecido'
    END AS action_name
FROM 
    audsys.aud$unified aud
JOIN 
    audit_actions act ON aud.action = act.action
    where aud.USERID='SYS' 
and aud.os_user <> 'oracle' 
and rownum < 100;



-- DML em tabelas de outros schemas
AUDIT SELECT ANY TABLE BY SESSION;
AUDIT INSERT ANY TABLE BY SESSION;
AUDIT UPDATE ANY TABLE BY SESSION;
AUDIT DELETE ANY TABLE BY SESSION;

-- Execução em objetos de outros schemas
AUDIT EXECUTE ANY PROCEDURE BY SESSION;
AUDIT EXECUTE ANY TYPE BY SESSION;
AUDIT EXECUTE ANY LIBRARY BY SESSION;

-- Sequences de outros schemas
AUDIT SELECT ANY SEQUENCE BY SESSION;

-- Dicionário de dados
AUDIT SELECT ANY DICTIONARY BY SESSION;

-- Materialized views de outros schemas
AUDIT SELECT ANY TABLE BY SESSION;

-- Índices, triggers, procedures em outros schemas
AUDIT ALTER ANY TABLE BY SESSION;
AUDIT ALTER ANY PROCEDURE BY SESSION;
AUDIT ALTER ANY TRIGGER BY SESSION;
AUDIT ALTER ANY INDEX BY SESSION;

-- DDL em outros schemas
AUDIT CREATE ANY TABLE BY SESSION;
AUDIT DROP ANY TABLE BY SESSION;
AUDIT CREATE ANY INDEX BY SESSION;
AUDIT DROP ANY INDEX BY SESSION;
AUDIT CREATE ANY VIEW BY SESSION;
AUDIT DROP ANY VIEW BY SESSION;
AUDIT CREATE ANY PROCEDURE BY SESSION;
AUDIT DROP ANY PROCEDURE BY SESSION;
AUDIT CREATE ANY TRIGGER BY SESSION;
AUDIT DROP ANY TRIGGER BY SESSION;
AUDIT CREATE ANY SEQUENCE BY SESSION;
AUDIT DROP ANY SEQUENCE BY SESSION;
AUDIT CREATE ANY SYNONYM BY SESSION;
AUDIT DROP ANY SYNONYM BY SESSION;
AUDIT CREATE ANY DIRECTORY BY SESSION;
AUDIT DROP ANY DIRECTORY BY SESSION;

-- Grants e privilégios
AUDIT GRANT ANY OBJECT PRIVILEGE BY SESSION;
AUDIT GRANT ANY PRIVILEGE BY SESSION;
AUDIT GRANT ANY ROLE BY SESSION;

-- Usuários e perfis
AUDIT CREATE USER BY SESSION;
AUDIT ALTER USER BY SESSION;
AUDIT DROP USER BY SESSION;
AUDIT ALTER PROFILE BY SESSION;
AUDIT DROP PROFILE BY SESSION;

-- Database links
AUDIT CREATE DATABASE LINK BY SESSION;
AUDIT DROP DATABASE LINK BY SESSION;
AUDIT CREATE PUBLIC DATABASE LINK BY SESSION;
AUDIT DROP PUBLIC DATABASE LINK BY SESSION;

-- Jobs e scheduler
AUDIT CREATE ANY JOB BY SESSION;
AUDIT EXECUTE ANY PROGRAM BY SESSION;

-- Links e sinônimos públicos
AUDIT DROP PUBLIC SYNONYM BY SESSION;
AUDIT CREATE PUBLIC SYNONYM BY SESSION;

-- Operações críticas
AUDIT ALTER SYSTEM BY SESSION;
AUDIT ALTER DATABASE BY SESSION;
AUDIT AUDIT SYSTEM BY SESSION;
AUDIT BECOME USER BY SESSION;
AUDIT ALTER TABLESPACE BY SESSION;
AUDIT CREATE TABLESPACE BY SESSION;
AUDIT DROP TABLESPACE BY SESSION;