-- Monitorar erros do TRACEGP_PROD após remoção da role
SELECT
  EVENT_TIMESTAMP,
  ACTION_NAME,
  OBJECT_SCHEMA,
  OBJECT_NAME,
  SYSTEM_PRIVILEGE_USED,
  RETURN_CODE
FROM UNIFIED_AUDIT_TRAIL
WHERE DBUSERNAME = 'TRACEGP_PROD'
  AND RETURN_CODE != 0
ORDER BY EVENT_TIMESTAMP DESC
FETCH FIRST 20 ROWS ONLY;