-- Volume por dia e usuário
SELECT
  TRUNC(EVENT_TIMESTAMP, 'DD') AS DIA,
  DBUSERNAME,
  COUNT(*) AS REGISTROS,
  ROUND(COUNT(*) * 148 / 1024 / 1024, 2) AS ESTIMATIVA_MB
FROM UNIFIED_AUDIT_TRAIL
WHERE DBUSERNAME = 'TRACEGP_PROD'
GROUP BY TRUNC(EVENT_TIMESTAMP, 'DD'), DBUSERNAME
ORDER BY DIA DESC;