---Exemplo de saida
--- SELECT ANY TABLE	SELECT	PROTHEUS12	SCR010	186
--- SELECT ANY TABLE	SELECT	PROTHEUS12	SC7010	2
SELECT DISTINCT
  SYSTEM_PRIVILEGE_USED,
  ACTION_NAME,
  OBJECT_SCHEMA,
  OBJECT_NAME,
  COUNT(*) AS TOTAL
FROM UNIFIED_AUDIT_TRAIL
WHERE DBUSERNAME = 'TRACEGP_PROD'
  AND SYSTEM_PRIVILEGE_USED IS NOT NULL
  AND SYSTEM_PRIVILEGE_USED != 'CREATE SESSION'
GROUP BY SYSTEM_PRIVILEGE_USED, ACTION_NAME, OBJECT_SCHEMA, OBJECT_NAME
ORDER BY SYSTEM_PRIVILEGE_USED, TOTAL DESC;