SELECT * FROM dba_audit_mgmt_config_params;


-- 1. Verificar se Unified Auditing está ativo
SELECT VALUE FROM V$OPTION WHERE PARAMETER = 'Unified Auditing';

-- 2. Verificar parâmetro audit_trail
SHOW PARAMETER AUDIT_TRAIL;

-- 3. Verificar tablespaces de todas as trilhas
SELECT PARAMETER_NAME, PARAMETER_VALUE, AUDIT_TRAIL
FROM DBA_AUDIT_MGMT_CONFIG_PARAMS
WHERE PARAMETER_NAME = 'DB AUDIT TABLESPACE'
ORDER BY AUDIT_TRAIL;

-- 4. Verificar timestamp de retenção
SELECT AUDIT_TRAIL, RAC_INSTANCE, LAST_ARCHIVE_TS
FROM DBA_AUDIT_MGMT_LAST_ARCH_TS
ORDER BY AUDIT_TRAIL, RAC_INSTANCE;

-- 5. Verificar jobs configurados
SELECT JOB_NAME, ENABLED, REPEAT_INTERVAL, NEXT_RUN_DATE
FROM DBA_SCHEDULER_JOBS
WHERE JOB_NAME IN ('PURGE_ALL_AUDIT_TRAILS', 'JOB_UPDATE_AUDIT_TIMESTAMP')
ORDER BY NEXT_RUN_DATE;

-- 6. Verificar política ativa
SELECT POLICY_NAME, ENABLED_OPT, USER_NAME, SUCCESS, FAILURE
FROM AUDIT_UNIFIED_ENABLED_POLICIES
WHERE POLICY_NAME = 'POL_AUDIT_TRACEGP_PROD';

-- 7. Verificar se está coletando registros
SELECT ACTION_NAME, OBJECT_SCHEMA, OBJECT_NAME,
       EVENT_TIMESTAMP, RETURN_CODE
FROM UNIFIED_AUDIT_TRAIL
WHERE DBUSERNAME = 'TRACEGP_PROD'
ORDER BY EVENT_TIMESTAMP DESC
FETCH FIRST 10 ROWS ONLY;

-- 8. Verificar objetos externos acessados
SELECT DISTINCT ACTION_NAME, OBJECT_SCHEMA, OBJECT_NAME, SYSTEM_PRIVILEGE_USED
FROM UNIFIED_AUDIT_TRAIL
WHERE DBUSERNAME = 'TRACEGP_PROD'
  AND OBJECT_SCHEMA IS NOT NULL
  AND OBJECT_SCHEMA NOT IN ('TRACEGP_PROD', 'SYS', 'PUBLIC')
ORDER BY OBJECT_SCHEMA, OBJECT_NAME, ACTION_NAME;

-- 9. Verificar grants diretos concedidos
SELECT OWNER, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'TRACEGP_PROD'
  AND OWNER IN ('DB_SECURITY','FIREWALLBD','PROTHEUS12','SYSTEM')
ORDER BY OWNER, TABLE_NAME;

-- 10. Verificar espaço da AUDIT_TRAIL
SELECT
  TABLESPACE_NAME,
  ROUND(SUM(BYTES)/1024/1024/1024, 2) AS GB_LIVRE
FROM DBA_FREE_SPACE
WHERE TABLESPACE_NAME = 'AUDIT_TRAIL'
GROUP BY TABLESPACE_NAME;