SELECT 'SYSTEM PRIV' AS TIPO,
       PRIVILEGE AS PRIVILEGIO
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'ACESSO_DBA'
UNION ALL
SELECT 'ROLE',
       GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'ACESSO_DBA';