/*  */
create role SLR_DISC_EDIT;
grant select on
DIMENSION.DIM_CUSTOMER to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_DAILY_CALENDAR to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_LOCATION to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_SAP_CARRIER to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_PRODUCT to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_ROUTE_CODE to SLR_DISC_EDIT;
grant select on DIMENSION.MTV_DIM_CUST_LOCATION to SLR_DISC_EDIT;
grant select on DIMENSION.LKP_ROUTE_DETERMINATION to SLR_DISC_EDIT;
grant select on DIMENSION.DIM_SHIPPING_POINT to SLR_DISC_EDIT;
grant select on DIMENSION.LKP_SAP_DESC to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_DELIVERY_HDR to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_DELIVERY_ITEM to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_DELIVERY_SHIPMENT_XREF to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_SHIPMENT_HDR to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_SHIPMENT_STAGE to SLR_DISC_EDIT;
grant select on KMSLR.ODS_SAP_SHIP_STG_STATS_HIST
to SLR_DISC_EDIT;
grant SLR_DISC_EDIT to GMPRATIC;
