/*  */
rem db_policies.sql
rem FUNCTION: SHow report on database policies
rem MRA
rem
COLUMN OBJECT_OWNER   FORMAT A12   HEADING 'Object|Owner'
COLUMN OBJECT_NAME    FORMAT A17   HEADING 'Object|Name'
COLUMN POLICY_NAME    FORMAT A15   HEADING 'Policy|Name'
COLUMN PF_OWNER       FORMAT A12   HEADING 'Policy|Function|Owner'
COLUMN PACKAGE        FORMAT A15   HEADING 'Functions|Package'
COLUMN FUNCTION       FORMAT A15   HEADING 'Function|Name'
COLUMN SEL            FORMAT A3   HEADING 'Sel|?'
COLUMN INS            FORMAT A3   HEADING 'Ins|?'
COLUMN UPD            FORMAT A3   HEADING 'Upd|?'
COLUMN DEL            FORMAT A3   HEADING 'Del|?'
COLUMN CHK_OPTION     FORMAT A3   HEADING 'Check|Option'
COLUMN ENABLE         FORMAT A3   HEADING 'Enabled?'
SET LINES 132 VERIFY OFF FEEDBACK OFF PAGES 47
START title132 'DB Policies Report'
BREAK ON object_owner
SPOOL rep_out\&db\db_policies
SELECT
  OBJECT_OWNER,
  OBJECT_NAME,
  POLICY_NAME,
  PF_OWNER,
  PACKAGE,
  FUNCTION,
  SEL,
  INS,
  UPD,
  DEL,
  CHK_OPTION,
  ENABLE
FROM
 DBA_POLICIES
ORDER BY 
 1,2,3;
SPOOL OFF
SET LINES 80 VERIFY ON FEEDBACK ON PAGES 22
CLEAR BREAKS
CLEAR COLUMNS
TTITLE OFF
