/*  */
set echo on
spool desc_def.lis
desc DEF$_CALL                                                                  
desc DEF$_ERROR                                                                 
desc DEF$_DESTINATION                                                           
desc DEF$_CALLDEST                                                              
desc DEF$_DEFAULTDEST                                                           
spool off
