/*  */
select owner from dba_tables where table_name in (
'ODS_KM_LOAD_SHIPMENT_DB2'
,'ODS_KM_LOAD_SHIPMENT_IMS'
,'ODS_KM_ORDER'
,'ODS_KM_SHIPMENT'
,'ODS_KM_SHIPMENT_LINE_ITEM'
,'ODS_KM_SHIPMENT_LINE_TRANS'
,'ODS_KM_SHIPMENT_LN_ITEM_OTHER'
,'ODS_KM_SHIPMENT_OTHER'
,'RJT_FJLGT2LSH0'
,'RJT_FJSHIPLOADIMS'
,'RJT_KM_ORDER'
,'RJT_KM_SHIPMENT'
,'RJT_KM_SHIPMENT_LINE_ITEM'
,'RJT_KM_SHIPMENT_LINE_TRANS'
,'ODS_KM_LOAD_ORDER_DB2' 
,'ODS_KM_LOAD_ORDER_IMS'
,'RJT_FJLGT2LOD0'
,'RJT_FJROOTLOADIMS')
/

