/*  */


REM
REM NAME        : RBK2.SQL
REM FUNCTION    : REPORT ON ROLLBACK SEGMENT STATISTICS
REM FUNCTION    : USES THE ROLLBACK2 VIEW
REM USE         : FROM SQLPLUS
REM Limitations : None
REM
COLUMN segment_name     FORMAT A8              HEADING 'ROLLBACK'
COLUMN extents          FORMAT 99999            HEADING 'EXTENTS'
COLUMN xacts            FORMAT 9999            HEADING 'TRANS'
COLUMN hwmsize          FORMAT 9999999999    HEADING 'LARGEST TRANS'
COLUMN rssize           FORMAT 9999999999    HEADING 'CUR SIZE'
COLUMN waits            FORMAT 99999              HEADING 'WAITS'
COLUMN wraps            FORMAT 99999              HEADING 'WRAPS'
COLUMN extends          FORMAT 9999              HEADING 'EXTENDS'
rem
SET FEEDBACK OFF VERIFY OFF lines 132 pages 58
BREAK ON REPORT
COMPUTE AVG OF WAITS ON REPORT
COMPUTE AVG OF WRAPS ON REPORT
COMPUTE AVG OF EXTENDS ON REPORT
COMPUTE AVG OF HWMSIZE ON REPORT
rem
@title132 "ROLLBACK SEGMENT STATISTICS"
SPOOL rep_out\&db\rbk2
rem
SELECT * FROM rollback2 ORDER BY segment_name;
SPOOL OFF
SET LINES 80 PAGES 20 FEEDBACK ON VERIFY ON 
TTITLE OFF
CLEAR COLUMNS
PAUSE Press enter to continue
