/*  */
/* cal_stat.sql */
/* FUNCTION: PLSQL script cal_stat.sql, used by do_calst.sql*/
create or replace procedure just_statistics as
    jdate date;
    jsec number;
    hr number;
    minute number;
    sec1 number;
    sec2 number;
    sec number;
    startup_date varchar2(64);
    dd_ratio number := 0; 
    R_CALLS NUMBER  := 0; 
    H_RATIO NUMBER  := 0; 
    SUHW_CONT  NUMBER  := 0;
    SUBW_CONT  NUMBER  := 0;
    UHW_CONT   NUMBER  := 0;
    UBW_CONT   NUMBER  := 0; 
    DB_GETS NUMBER  := 0; 
    CON_GETS NUMBER := 0; 
    P_READS NUMBER  := 0; 
    SUH_WAITS NUMBER := 0;
    SUB_WAITS NUMBER := 0; 
    UH_WAITS NUMBER := 0; 
    UB_WAITS NUMBER := 0;  
    U_CALLS NUMBER  := 0; 
    CALLS_U NUMBER  := 0; 
    RLOG_WAIT NUMBER := 0; 
    STAT_NAME varCHAR2(64); 
    TEMP_NAME varCHAR2(64); 
    STAT_VAL NUMBER := 0;
    temp_value number := 0; 

cursor get_latch is
SELECT 
	A.NAME,100.*B.SLEEPS/B.GETS 
FROM
   	V$LATCHNAME A, V$LATCH B 
WHERE
   	A.LATCH# = B.LATCH# AND B.SLEEPS > 0;

cursor get_totals is
select 
	object_type,count(*)
from 
	dba_objects
where 
	owner not in ('SYS','SYSTEM')
group by 
	object_type
order by 
	object_type;

cursor get_stat(stat in varchar2) is
select 
	name,value 
from 
	v$sysstat 
where 
	NAME = STAT;

cursor get_count(stat in varchar2) is
select 
	class,"COUNT" 
from 
	v$waitstat  
where 
	CLASS = STAT_NAME; 

BEGIN 
  DELETE DBA_TEMP;
begin
	select to_date(to_number(value,'99999999'),'J') into jdate from
		v$instance where key='STARTUP TIME - JULIAN';
	select (to_number(value,'9999999')) into jsec from v$instance
		where key='STARTUP TIME - SECONDS';
	hr:=trunc(jsec/3600,0);
	minute:= trunc(((jsec/3600)-hr)*60,0);
	sec:= trunc((((((jsec/3600)-hr)*60)-minute)*60),0);
	startup_date:=jdate||' '||to_char(hr)||':'||to_char(minute)||':'||
	to_char(sec);
	insert into dba_temp values ('Startup Date: '||startup_date,0,1);
EXCEPTION
    when no_data_found then
	insert into dba_temp values ('Startup Date: unknown',0,1);
end; 
begin
  STAT_NAME := 'recursive calls';
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, r_calls;
	close get_stat;
EXCEPTION
    when no_data_found then
close get_stat;
end; 
begin  
  STAT_NAME := 'Data Dictionary Miss Percent'; 
	select stat_name, (sum(getmisses)/sum(gets))*100 into TEMP_name, dd_ratio 
	from v$rowcache; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, dd_ratio,17); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,17); 
    commit; 
end; 
begin 
  STAT_NAME := 'user calls'; 
	open  get_stat(stat_name);
	fetch get_stat into TEMP_name, u_calls;
	close get_stat;
EXCEPTION 
    when no_data_found then 
close get_stat;
end; 
begin 
  STAT_NAME := 'db block gets'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, db_gets;
	close get_stat;
EXCEPTION 
    when no_data_found then 
close get_stat;
end; 
begin 
  STAT_NAME := 'consistent gets'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, con_gets;
	close get_stat;
EXCEPTION 
    when no_data_found then 
close get_stat;
end; 
begin 
  STAT_NAME := 'physical reads'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, p_reads;
	close get_stat;
EXCEPTION 
    when no_data_found then 
close get_stat;
end; 
begin 
  STAT_NAME := 'system undo header'; 
	open get_count(stat_name);
	fetch get_count into TEMP_name, suh_waits;
	close get_count;
EXCEPTION 
    when no_data_found then 
close get_count;
end; 
begin 
  STAT_NAME := 'system undo block'; 
	open get_count(stat_name);
	fetch get_count into TEMP_name, sub_waits;
	close get_count;
EXCEPTION 
    when no_data_found then 
close get_count;
end; 
begin 
  STAT_NAME := 'undo header'; 
	open get_count(stat_name);
	fetch get_count into TEMP_name, uh_waits;
	close get_count;
EXCEPTION 
    when no_data_found then 
close get_count;
end; 
begin 
  STAT_NAME := 'undo block'; 
	open get_count(stat_name);
	fetch get_count into TEMP_name, ub_waits;
	close get_count;
EXCEPTION 
    when no_data_found then 
close get_count;
end; 
begin 
    CALLS_U := (R_CALLS/U_CALLS); 
    H_RATIO := ((DB_GETS+CON_GETS)/(DB_GETS+CON_GETS+P_READS)); 
    SUHW_CONT  := (SUH_WAITS/(DB_GETS+CON_GETS)*100);
    SUBW_CONT  := (SUB_WAITS/(DB_GETS+CON_GETS)*100);
    UHW_CONT  := (UH_WAITS/(DB_GETS+CON_GETS)*100);
    UBW_CONT  := (UB_WAITS/(DB_GETS+CON_GETS)*100);
  STAT_NAME := 'RECURSIVE CALLS PER USER'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, CALLS_U,18); 
  STAT_NAME := 'CUMMULATIVE HIT RATIO'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, H_RATIO,2); 
  STAT_NAME := 'SYS UNDO HDR WAIT CONTENTION'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, SUHW_CONT,3); 
  STAT_NAME := 'SYS UNDO BLK WAIT CONTENTION'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, SUBW_CONT,3); 
  STAT_NAME := 'UNDO HDR WAIT CONTENTION'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, UHW_CONT,3);
  STAT_NAME := 'UNDO BLK WAIT CONTENTION'; 
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, UBW_CONT,3);  
  STAT_NAME := 'freelist'; 
	open get_count(stat_name);
	fetch get_count into TEMP_name, stat_val;
	close get_count;
  STAT_NAME := 'Free List Contention Ratio';
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL/(db_gets+con_gets),18); 
EXCEPTION 
    WHEN ZERO_DIVIDE THEN 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,32);
	close get_count; 
    COMMIT; 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,32); 
	close get_count;
    commit; 
end; 
/* If post 7.2 uncomment this next block */
/*begin
  STAT_NAME := 'Latch Miss%'; 
	select (1-((sum(sleeps)+sum(immediate_misses))/(
	sum(gets)+sum(immediate_misses)+sum(immediate_gets)))*100) into stat_val 
	from v$latch;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,4); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,4); 
    commit; 
end; */
begin
  STAT_NAME := 'Rollback Wait %'; 
	select (sum(waits)/sum(gets))*100 into stat_val 
	from v$rollstat;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,5); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,5); 
    commit; 
end; 
begin
  STAT_NAME := 'Library Reload %'; 
	select sum(reloads)/sum(pins)*100  into stat_val 
	from v$librarycache;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,5); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,5); 
    commit; 
end; 
begin
  STAT_NAME := 'table fetch by rowid';
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,9);
EXCEPTION
    when no_data_found then
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,9);
close get_stat;
    commit;
end;
begin
  STAT_NAME:='Non-Index Lookups Ratio';
  select a.value/(a.value+b.value) into STAT_VAL
   from v$sysstat a, v$sysstat b
   where a.name='table scans (long tables)' 
   and b.name='table scans (short tables)';
       INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,8); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,8); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'table fetch continued row'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,14); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,14); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'sorts (memory)'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
    INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,15); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,15); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'sorts (disk)'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,16); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,16); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'redo log space requests'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,6); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,6); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'redo log space wait time'; 
	open get_stat(stat_name);
	fetch get_stat into TEMP_name, stat_val;
	close get_stat;
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL, 6); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,6); 
	close get_stat;
    commit; 
end; 
begin 
  STAT_NAME := 'TOTAL ALLOCATED MEG'; 
	select SUM(BYTES)/1048576 into stat_val 
	from dba_DATA_FILES where 
	STATUS = 'AVAILABLE'; 
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,25); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,25); 
    commit; 
end; 
begin 
  STAT_NAME := 'TOTAL USED MEG'; 
	select SUM(BYTES)/1048576 into stat_val 
	from dba_EXTENTS; 
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,26); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,26); 
    commit; 
end; 
begin 
  STAT_NAME := 'TOTAL SGA SIZE'; 
	select STAT_NAME, SUM(b.value) into TEMP_NAME, stat_val 
	from v$sGA b; 
  INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,31); 
EXCEPTION 
    when no_data_found then 
	INSERT INTO DBA_TEMP VALUES (STAT_NAME,0,31); 
    commit; 
end; 
begin
open get_latch;
loop
	fetch get_latch into stat_name,stat_val;
	exit when get_latch%NOTFOUND;
  	INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,33);
end loop;
	close get_latch;
	commit;
end; 
begin
open get_totals;
loop
	fetch get_totals into stat_name,stat_val;
	exit when get_totals%NOTFOUND;
  	INSERT INTO DBA_TEMP VALUES (STAT_NAME, STAT_VAL,34);
end loop;
	close get_totals;
	commit;
end; 
  COMMIT; 
END;         
/
