set pagesize 999
set linesize 171

COLUMN OWNER FORMAT A30
COLUMN CONSTRAINT_NAME FORMAT A30
COLUMN TYPE FORMAT A4
COLUMN TABLE_NAME FORMAT A30
COLUMN R_OWNER FORMAT A30
COLUMN R_CONSTRAINT_NAME FORMAT A30
COLUMN STATUS FORMAT A8
COLUMN DEFERRABLE FORMAT A10
COLUMN DEFERRED FORMAT A8
COLUMN VALIDATED FORMAT A9

SELECT OWNER
     , CONSTRAINT_NAME
     , decode(constraint_type
	   ,'P', 'PK'
	   ,'R', 'FK'
	   ,'U', 'UK'
	   ,'C', 'CHK'		
	   ,'V', 'VCHK'
	   ,'O', 'VRDO'
		   , constraint_type
	  ) TYPE
     , TABLE_NAME
     , R_OWNER
     , R_CONSTRAINT_NAME
     , STATUS
     , DECODE(DEFERRABLE, 'DEFERRABLE', 'YES', 'NO') DEFERRABLE
     , SUBSTR(DEFERRED, 1, 8) DEFERRED
     , DECODE(VALIDATED, 'VALIDATED', 'YES', 'NO') VALIDATED
  FROM DBA_CONSTRAINTS
 WHERE OWNER LIKE NVL('&LOWNER', OWNER)
   AND TABLE_NAME LIKE NVL('&LKTABLE', TABLE_NAME)
   AND CONSTRAINT_NAME LIKE NVL('&LKCONSNAME', CONSTRAINT_NAME)
/
