COL INDEX_OWNER FORMAT A30
COL INDEX_NAME FORMAT A30
COL TABLE_OWNER FORMAT A30
COL TABLE_NAME FORMAT A30
COL COLUMN_NAME FORMAT A30
COL COLUMN_POSITION FORMAT 99999999999999
COL COLUMN_LENGTH FORMAT 99999999999999
COL CHAR_LENGTH FORMAT 99999999999999
COL DESCEND FORMAT A7

SELECT INDEX_OWNER
     , INDEX_NAME
     , TABLE_OWNER
     , TABLE_NAME
     , COLUMN_NAME
     , COLUMN_POSITION
     , COLUMN_LENGTH
     , CHAR_LENGTH
     , DESCEND
  FROM DBA_IND_COLUMNS DIC
 WHERE DIC.INDEX_NAME LIKE UPPER(NVL('&LK_IND_NAME', INDEX_NAME))
   AND DIC.TABLE_OWNER = UPPER(NVL('&TABLE_OWNER', TABLE_OWNER))
   AND DIC.TABLE_NAME = UPPER(NVL('&TABLE_NAME', TABLE_NAME))
/