set linesize 500
set pagesize 9999

COL OWNER FORMAT A30
COL OBJECT_NAME FORMAT A30
COL SUBOBJECT_NAME FORMAT A30
COL OBJECT_ID FORMAT 99999999999999
COL DATA_OBJECT_ID FORMAT 99999999999999
COL OBJECT_TYPE FORMAT A19
COL CREATED FORMAT A21
COL LAST_DDL_TIME FORMAT A21
COL TIMESTAMP FORMAT A19
COL STATUS FORMAT A7
COL TEMPORARY FORMAT A9
COL GENERATED FORMAT A9
COL SECONDARY FORMAT A9

SELECT OWNER
     , OBJECT_NAME
     , SUBOBJECT_NAME
     , OBJECT_ID
     , DATA_OBJECT_ID
     , OBJECT_TYPE
     , CREATED
     , LAST_DDL_TIME
     , TIMESTAMP
     , STATUS
     , TEMPORARY
     , GENERATED
     , SECONDARY
  from DBA_OBJECTS
 where OBJECT_NAME like UPPER(nvl('&LK_OBJECT', OBJECT_NAME))
   and OWNER = UPPER(NVL('&OWNER', OWNER))
   and OBJECT_TYPE = UPPER(NVL('&OBJECT_TYPE', OBJECT_TYPE))
   and STATUS = UPPER(NVL('&STATUS', STATUS))
/
