set pagesize 9999
set linesize 5000

COL OWNER FORMAT A30
COL INDEX_NAME FORMAT A30
COL TABLE_NAME FORMAT A30
COL PART_TYPE FORMAT A9
COL SUBPART_TYPE FORMAT A12
COL PARTITION_COUNT FORMAT 99999999999999
COL DEF_SUBPARTITION_COUNT FORMAT 99999999999999
COL PARTITIONING_KEY_COUNT FORMAT 99999999999999
COL SUBPARTITIONING_KEY_COUNT FORMAT 99999999999999
COL LOCALITY FORMAT A8
COL ALIGNMENT FORMAT A12
COL DEF_TABLESPACE_NAME FORMAT A30
COL DEF_PCT_FREE FORMAT 99999999999999
COL DEF_INI_TRANS FORMAT 99999999999999
COL DEF_MAX_TRANS FORMAT 99999999999999
COL DEF_INITIAL_EXTENT FORMAT A40
COL DEF_NEXT_EXTENT FORMAT A40
COL DEF_MIN_EXTENTS FORMAT A40
COL DEF_MAX_EXTENTS FORMAT A40
COL DEF_PCT_INCREASE FORMAT A40
COL DEF_FREELISTS FORMAT 99999999999999
COL DEF_FREELIST_GROUPS FORMAT 99999999999999
COL DEF_LOGGING FORMAT A12
COL DEF_BUFFER_POOL FORMAT A15
COL DEF_PARAMETERS FORMAT A1000

SELECT OWNER
     , INDEX_NAME
     , TABLE_NAME
     , PARTITIONING_TYPE PART_TYPE
     , SUBPARTITIONING_TYPE SUBPART_TYPE
     , PARTITION_COUNT
     , DEF_SUBPARTITION_COUNT
     , PARTITIONING_KEY_COUNT
     , SUBPARTITIONING_KEY_COUNT
     , LOCALITY
     , ALIGNMENT
     , DEF_TABLESPACE_NAME
     , DEF_PCT_FREE
     , DEF_INI_TRANS
     , DEF_MAX_TRANS
     , DEF_INITIAL_EXTENT
     , DEF_NEXT_EXTENT
     , DEF_MIN_EXTENTS
     , DEF_MAX_EXTENTS
     , DEF_PCT_INCREASE
     , DEF_FREELISTS
     , DEF_FREELIST_GROUPS
     , DEF_LOGGING
     , DEF_BUFFER_POOL
     , DEF_PARAMETERS
  FROM DBA_PART_INDEXES
 WHERE OWNER = UPPER(NVL('&OWNER', OWNER))
   AND TABLE_NAME = UPPER(NVL('&TABLE_NAME', TABLE_NAME))
   AND INDEX_NAME LIKE UPPER(NVL('&LK_INDEX_NAME', INDEX_NAME))
/

prompt 
prompt consider to run dindpartitions.sql or getindpartval.sql
prompt
