@reset

COL COMP_ID FORMAT A30
COL COMP_NAME FORMAT A30
COL VERSION FORMAT A30
COL STATUS FORMAT A11
COL MODIFIED FORMAT A20
COL NAMESPACE FORMAT A15
COL CONTROL FORMAT A10
COL SCHEMA FORMAT A10
COL PROCEDURE FORMAT A61
COL STARTUP FORMAT A8
COL PARENT_ID FORMAT A30
COL OTHER_SCHEMAS FORMAT A30

SELECT COMP_ID
     , STATUS
     , VERSION
     , substr(COMP_NAME,1,30) COMP_NAME
     , substr(NAMESPACE,1,15) NAMESPACE
     , CONTROL
     , SCHEMA
     , MODIFIED
     , PROCEDURE
     , STARTUP
     , PARENT_ID
     , substr(OTHER_SCHEMAS,1,30) OTHER_SCHEMAS
  FROM DBA_REGISTRY
/