set linesize 200
set pagesize 999

col GRANTEE format a30
col GRANTED_ROLE format a30
col ADMIN_OPTION format a12
col DEFAULT_ROLE format a12

SELECT GRANTEE
     , GRANTED_ROLE
     , ADMIN_OPTION
     , DEFAULT_ROLE
  FROM DBA_ROLE_PRIVS
 WHERE GRANTEE like UPPER(NVL('&LGRANTEE', GRANTEE))
   AND GRANTED_ROLE like UPPER(NVL('&GRANTED_ROLE', GRANTED_ROLE))
/