set linesize 160
set pagesize 10
COLUMN OWNER FORMAT a10
COLUMN SYNONYM_NAME FORMAT a30
COLUMN TABLE_OWNER FORMAT a30
COLUMN TABLE_NAME FORMAT a30
COLUMN DB_LINK FORMAT a50

select OWNER
     , SYNONYM_NAME
     , TABLE_OWNER
     , TABLE_NAME
     , DB_LINK
  from DBA_SYNONYMS S
 where S.SYNONYM_NAME like UPPER(NVL('&SYNONYM',SYNONYM_NAME))
   and S.TABLE_OWNER like UPPER(NVL('&TABLEOWNER',TABLE_OWNER))
 order by OWNER, SYNONYM_NAME
/
