set pagesize 999
set linesize 5000

COL "TABLE" FORMAT A61
COL TABLE_TYPE FORMAT A11
COL COMMENTS FORMAT A4000

SELECT OWNER||'.'||TABLE_NAME "TABLE"
     , TABLE_TYPE
     , COMMENTS
  FROM DBA_TAB_COMMENTS
 WHERE OWNER LIKE NVL('&LOWNER', OWNER)
   AND TABLE_NAME LIKE NVL('&LTABLE_NAME', TABLE_NAME)
/

set linesize 165