set linesize 300
COLUMN OWNER FORMAT A30
COLUMN TABLE_NAME FORMAT A30
COLUMN TBS_NAME FORMAT A30
COLUMN LOGGING FORMAT A30
COLUMN NUM_ROWS FORMAT 9999999999
SELECT OWNER
     , TABLE_NAME
     , TABLESPACE_NAME TBS_NAME
     , LOGGING
     , NUM_ROWS
  FROM DBA_TABLES DBAT
 WHERE OWNER = upper(nvl('&OWNER', OWNER))
   AND TABLE_NAME like upper(nvl('&LKTABLE', TABLE_NAME))
/
