set pagesize 999
set linesize 200

COLUMN GRANTEE    FORMAT A30
COLUMN OWNER      FORMAT A30
COLUMN TABLE_NAME FORMAT A30
COLUMN GRANTOR    FORMAT A30
COLUMN PRIVILEGE  FORMAT A30
COLUMN GRANTABLE  FORMAT A9
COLUMN HIERARCHY  FORMAT A9

SELECT GRANTEE
     , OWNER
     , TABLE_NAME
     , GRANTOR
     , PRIVILEGE
     , GRANTABLE
     , HIERARCHY
  FROM DBA_TAB_PRIVS
 WHERE GRANTEE LIKE NVL('&LKGRANTEE', GRANTEE)
   AND OWNER LIKE NVL('&LKOWNER', OWNER)
   AND TABLE_NAME LIKE NVL('&LKTABLE', 'TABLE_NAME')
 ORDER BY TABLE_NAME
/
