set linesize 500
set pagesize 999

COLUMN TABLESPACE_NAME   FORMAT A30
COLUMN STATUS            FORMAT A9
COLUMN CONTENTS          FORMAT A9
COLUMN LOGGING           FORMAT A9
COLUMN EXTENT_MANAGEMENT FORMAT A10
COLUMN ALLOCATION_TYPE	 FORMAT A9
COLUMN SEGMENT_SPACE_MANAGEMENT FORMAT A6

SELECT TABLESPACE_NAME
     , STATUS
     , CONTENTS
     , LOGGING
     , EXTENT_MANAGEMENT
     , ALLOCATION_TYPE
     , SEGMENT_SPACE_MANAGEMENT
  FROM DBA_TABLESPACES
 WHERE TABLESPACE_NAME LIKE nvl('&TBSLIKE',TABLESPACE_NAME)
/
