set pagesize 20
set linesize 5000

COLUMN OWNER FORMAT A30
COLUMN TRIGGER_NAME FORMAT A30
COLUMN TRIGGER_TYPE FORMAT A16
COLUMN EVENT_SHORT  FORMAT A30
COLUMN TRIGGERING_EVENT FORMAT A227
COLUMN TABLE_OWNER FORMAT A30
COLUMN BASE_OBJECT_TYPE FORMAT A16
COLUMN TABLE_NAME FORMAT A30
COLUMN COLUMN_NAME FORMAT A200
COLUMN REFERENCING_NAMES FORMAT A128
COLUMN WHEN_CLAUSE FORMAT A500
COLUMN STATUS FORMAT A8
COLUMN DESCRIPTION FORMAT A500
COLUMN ACTION_TYPE FORMAT A11

SELECT OWNER
     , TRIGGER_NAME
     , TRIGGER_TYPE
     , substr(TRIGGERING_EVENT, 1, 30) EVENT_SHORT
     , STATUS	 
     , TABLE_OWNER
     , BASE_OBJECT_TYPE
     , TABLE_NAME
	 , TRIGGERING_EVENT
     , substr(COLUMN_NAME, 1, 500) COLUMN_NAME
     , REFERENCING_NAMES
     , substr(replace(WHEN_CLAUSE, chr(10), ' '), 1, 500) WHEN_CLAUSE
     , substr(replace(DESCRIPTION, chr(10), ' '), 1, 500) DESCRIPTION
     , ACTION_TYPE
  FROM DBA_TRIGGERS
 WHERE TABLE_OWNER = NVL('&TABOWNER', TABLE_OWNER)
   AND (   (TABLE_NAME = NVL('&TABNAME', TABLE_NAME) AND TABLE_NAME IS NOT NULL)
         OR TABLE_NAME IS NULL
       )
   AND TRIGGER_NAME like NVL('&TRIGGERNAME', TRIGGER_NAME)
/

@reset