set pagesize 999
set linesize 200

COL USERNAME FORMAT A30
COL TABLESPACE_NAME FORMAT A30
COL USED_MB FORMAT 9999999
COL MAX_MB FORMAT A9
COL BLOCKS FORMAT 9999999999999999
COL MAX_BLOCKS FORMAT A20
COL DROPPED FORMAT A7
COL "%FREE_MB" FORMAT A9
COL ATTENTION FORMAT A9

SELECT USERNAME
     , TABLESPACE_NAME
     , (BYTES/1024/1024) USED_MB
     , decode(MAX_BYTES, -1, 'UNLIMITED', MAX_BYTES/1024/1024) MAX_MB
     , BLOCKS
     , decode(MAX_BLOCKS, -1, 'UNLIMITED', MAX_BLOCKS) MAX_BLOCKS
     , DROPPED
     , decode(MAX_BYTES, -1, 'UNLIMITED', 100 - round(BYTES * 100 / MAX_BYTES, 2)) "%FREE_MB"
     , case when MAX_BYTES = -1
            then ' '
            when 100 - round(BYTES * 100 / MAX_BYTES, 2) <= 10
            then '<======'
       end ATTENTION
  FROM DBA_TS_QUOTAS
 WHERE USERNAME like NVL('&LUSERNAME', USERNAME)
   AND TABLESPACE_NAME like NVL('&TBS_NAME', TABLESPACE_NAME)
 ORDER BY round(BYTES * 100 / MAX_BYTES, 2) asc
/
