set linesize 5000
set pagesize 9999

COL OWNER FORMAT A30
COL TYPE_NAME FORMAT A30
COL ATTR_NAME FORMAT A30
COL ATTR_TYPE_MOD FORMAT A28
COL ATTR_TYPE_OWNER FORMAT A30
COL ATTR_TYPE_NAME FORMAT A30
COL LENGTH FORMAT 99999999999999
COL PRECISION FORMAT 99999999999999
COL SCALE FORMAT 99999999999999
COL CHARACTER_SET_NAME FORMAT A176
COL ATTR_NO FORMAT 99999999999999
COL INHERITED FORMAT A12

SELECT OWNER
     , TYPE_NAME
     , ATTR_NAME
     , ATTR_TYPE_MOD
     , ATTR_TYPE_OWNER
     , ATTR_TYPE_NAME
	 , '('||decode(SCALE, null, nvl(PRECISION, LENGTH), PRECISION||','||SCALE)||')' DLENGTH
     , LENGTH
     , PRECISION
     , SCALE
     , CHARACTER_SET_NAME
     , ATTR_NO
     , INHERITED
  FROM DBA_TYPE_ATTRS
 WHERE OWNER = UPPER(NVL('&OWNER', OWNER))
   AND TYPE_NAME = UPPER(NVL('&TYPE_NAME', TYPE_NAME))
 ORDER BY ATTR_NO
/