SELECT USERNAME
     , USER_ID
     , ACCOUNT_STATUS
     , EXPIRY_DATE
     , LOCK_DATE
     , TRUNC(EXPIRY_DATE - SYSDATE) DAYS_LEFT
     , PASSWORD
     , DEFAULT_TABLESPACE
     , TEMPORARY_TABLESPACE
     , CREATED
     , PROFILE
     , INITIAL_RSRC_CONSUMER_GROUP
     , EXTERNAL_NAME
  FROM DBA_USERS DU
 WHERE &DAYS_LEFT >= EXPIRY_DATE - SYSDATE
   AND EXPIRY_DATE >= SYSDATE
   AND ACCOUNT_STATUS = 'OPEN'
 ORDER BY USERNAME
/
