EXPLAIN PLAN
SET STATEMENT_ID = 'tq1'
FOR
SELECT DISTINCT R.CD_PROC_TAG FROM THROUGHFARE_RULE F ,ATP_CATEGORIA_VOLUNTARY_CHANGE S ,ATP_SERIE_REISSUE R WHERE F.FK_THFARE_AD_SEQ_THROUGH = :B2 AND F.NR_CATEGORIA_REGRA = 31 AND F.CD_TABELA_CATEGORIA = S.CD_TABELA_CAT AND S.FK_ATPSR_AD_SEQ_SERIE_REISSUE = R.CD_TABELA_CAT AND NVL(:B1 ,SYSDATE) >= F.DT_EFETIVAR AND NVL(:B1 ,SYSDATE) <= F.DT_DESCONTINUAR AND NVL(:B1 ,SYSDATE) >= S.DT_EFETIVAR AND NVL(:B1 ,SYSDATE) <= S.DT_DESC AND NVL(:B1 ,SYSDATE) >= R.DT_EFETIVAR AND NVL(:B1 ,SYSDATE) <= R.DT_DESCONTINUAR
/
select *  
FROM plan_table
START WITH id = 0 AND statement_id = 'tq1'
CONNECT BY PRIOR id = parent_id AND statement_id ='tq1';
delete from plan_table where statement_id = 'tq1';
commit;

