SET VERIFY OFF

set line 1000
col OBSERVACOES for 200

SELECT INSTANCE_NAME, INSTANCE_ALIAS, HOSTNAME, USUARIO_SO, VERSAO_BANCO, STATUS, RAC, ASM, DATABASE_CRIADO_POR, DESCRICAO_APLICACAO, OBSERVACOES
  FROM DBAPROD.INSTANCIA
 WHERE (UPPER(INSTANCE_NAME) LIKE UPPER('%&1%') OR UPPER(HOSTNAME) LIKE UPPER('%&1%'))
 ORDER BY INSTANCE_ALIAS, HOSTNAME;
 
UNDEFINE 1
SET VERIFY ON