	SELECT 'COL '
		|| COLUMN_NAME
		|| ' FORMAT '
		|| CASE WHEN DATA_TYPE IN ('CHAR','CLOB','VARCHAR2','NCHAR','NVARCHAR2','NCLOB')
		        THEN 'A'|| case when decode(DATA_LENGTH, 0, length(COLUMN_NAME), DATA_LENGTH) <= length(COLUMN_NAME)
				                then length(COLUMN_NAME) 
								else decode(DATA_LENGTH, 0, length(COLUMN_NAME), DATA_LENGTH)
						   end
				WHEN DATA_TYPE IN ('DATE')
				THEN 'A21'
				WHEN DATA_TYPE = 'LONG'
				THEN 'L9999'
		        WHEN DATA_TYPE IN ('FLOAT','NUMBER')
				THEN DECODE(DATA_SCALE, NULL, LPAD(9, NVL(DATA_PRECISION, decode(DATA_LENGTH, 22, 14, DATA_LENGTH)), 9), LPAD(9, DATA_PRECISION, 9)||DECODE(DATA_SCALE, 0, NULL, ','||LPAD(9, DATA_SCALE, 9)))
		        ELSE 'A20'
	       END FORMAT
	  FROM DBA_TAB_COLUMNS 
	 WHERE OWNER = UPPER('&OWNER')
	   AND TABLE_NAME = UPPER('&TABLE_NAME')
	 ORDER BY COLUMN_ID
/