SET PAGESIZE 999
SET LINESIZE 160

SELECT 'GRANT '||PRIVILEGE||' ON '||OWNER||'.'||TABLE_NAME||' TO '||GRANTEE||DECODE(GRANTABLE,'YES',' WITH GRANT OPTION;',';') COMMAND
  FROM DBA_TAB_PRIVS DT
 WHERE GRANTEE LIKE NVL('&LKGRANTEE', GRANTEE)
   AND OWNER = NVL('&OWNER', OWNER)
   AND TABLE_NAME = NVL('&TABLE', TABLE_NAME)
 ORDER BY GRANTEE
/