clear columns
set pagesize 9999
set linesize 5000
set long 50000

COL INDEX_OWNER FORMAT A30
COL INDEX_NAME FORMAT A30
COL PARTITION_NAME FORMAT A30
COL HIGH_VALUE_LENGTH FORMAT 99999999999999
COL TABLESPACE_NAME FORMAT A30

SELECT INDEX_OWNER
     , INDEX_NAME
     , PARTITION_NAME
     , HIGH_VALUE
     , HIGH_VALUE_LENGTH
     , TABLESPACE_NAME
  FROM DBA_IND_PARTITIONS
 WHERE INDEX_OWNER = UPPER(NVL('&INDEX_OWNER', INDEX_OWNER))
   AND INDEX_NAME = UPPER(NVL('&INDEX_NAME', INDEX_NAME))
   AND PARTITION_NAME LIKE UPPER(NVL('&PARTITION_NAME', PARTITION_NAME))
/

prompt 
prompt consider to run getindpartval.sql
prompt
