clear columns
set pagesize 9999
set linesize 5000
set long 50000

COL TABLE_OWNER FORMAT A30
COL TABLE_NAME FORMAT A30
COL PARTITION_NAME FORMAT A30
COL HIGH_VALUE_LENGTH FORMAT 99999999999999
COL TABLESPACE_NAME FORMAT A30

SELECT TABLE_OWNER
     , TABLE_NAME
     , PARTITION_NAME
     , HIGH_VALUE
     , HIGH_VALUE_LENGTH
     , TABLESPACE_NAME
  FROM DBA_TAB_PARTITIONS
 WHERE TABLE_OWNER = UPPER(NVL('&TABLE_OWNER', TABLE_OWNER))
   AND TABLE_NAME = UPPER(NVL('&TABLE_NAME', TABLE_NAME))
   AND PARTITION_NAME LIKE UPPER(NVL('&LK_PARTITION_NAME', PARTITION_NAME))
/

prompt 
prompt consider to run gettabpartval.sql
prompt
