@reset

COL INST_ID FORMAT 99999999999999
COL DBID FORMAT 99999999999999
COL NAME FORMAT A9
COL CREATED FORMAT A21
COL RESETLOGS_CHANGE# FORMAT 99999999999999
COL RESETLOGS_TIME FORMAT A21
COL PRIOR_RESETLOGS_CHANGE# FORMAT 99999999999999
COL PRIOR_RESETLOGS_TIME FORMAT A21
COL LOG_MODE FORMAT A12
COL CHECKPOINT_CHANGE# FORMAT 99999999999999
COL ARCHIVE_CHANGE# FORMAT 99999999999999
COL CONTROLFILE_TYPE FORMAT A16
COL CONTROLFILE_CREATED FORMAT A21
COL CONTROLFILE_SEQUENCE# FORMAT 99999999999999
COL CONTROLFILE_CHANGE# FORMAT 99999999999999
COL CONTROLFILE_TIME FORMAT A21
COL OPEN_RESETLOGS FORMAT A14
COL VERSION_TIME FORMAT A21
COL OPEN_MODE FORMAT A20
COL PROTECTION_MODE FORMAT A20
COL PROTECTION_LEVEL FORMAT A20
COL REMOTE_ARCHIVE FORMAT A14
COL ACTIVATION# FORMAT 99999999999999
COL SWITCHOVER# FORMAT 99999999999999
COL DATABASE_ROLE FORMAT A16
COL ARCHIVELOG_CHANGE# FORMAT 99999999999999
COL ARCHIVELOG_COMPRESSION FORMAT A22
COL SWITCHOVER_STATUS FORMAT A20
COL DATAGUARD_BROKER FORMAT A16
COL GUARD_STATUS FORMAT A12
COL SUPPLEMENTAL_LOG_DATA_MIN FORMAT A25
COL SUPPLEMENTAL_LOG_DATA_PK FORMAT A24
COL SUPPLEMENTAL_LOG_DATA_UI FORMAT A24
COL FORCE_LOGGING FORMAT A13
COL PLATFORM_ID FORMAT 99999999999999
COL PLATFORM_NAME FORMAT A101
COL RECOVERY_TARGET_INCARNATION# FORMAT 99999999999999
COL LAST_OPEN_INCARNATION# FORMAT 99999999999999
COL CURRENT_SCN FORMAT 99999999999999
COL FLASHBACK_ON FORMAT A18
COL SUPPLEMENTAL_LOG_DATA_FK FORMAT A24
COL SUPPLEMENTAL_LOG_DATA_ALL FORMAT A25
COL DB_UNIQUE_NAME FORMAT A30
COL STANDBY_BECAME_PRIMARY_SCN FORMAT 99999999999999
COL FS_FAILOVER_STATUS FORMAT A22
COL FS_FAILOVER_CURRENT_TARGET FORMAT A30
COL FS_FAILOVER_THRESHOLD FORMAT 99999999999999
COL FS_FAILOVER_OBSERVER_PRESENT FORMAT A28
COL FS_FAILOVER_OBSERVER_HOST FORMAT A512
COL CONTROLFILE_CONVERTED FORMAT A21
COL PRIMARY_DB_UNIQUE_NAME FORMAT A30
COL SUPPLEMENTAL_LOG_DATA_PL FORMAT A24
COL MIN_REQUIRED_CAPTURE_CHANGE# FORMAT 99999999999999

SELECT INST_ID
     , DBID
     , NAME
     , DB_UNIQUE_NAME
     , OPEN_MODE
     , LOG_MODE
     , FLASHBACK_ON
     , CURRENT_SCN
     , OPEN_RESETLOGS
     , DATABASE_ROLE
     , DATAGUARD_BROKER
     , GUARD_STATUS
     , CREATED
     , RESETLOGS_CHANGE#
     , RESETLOGS_TIME
     , PRIOR_RESETLOGS_CHANGE#
     , PRIOR_RESETLOGS_TIME
     , CHECKPOINT_CHANGE#
     , ARCHIVE_CHANGE#
     , CONTROLFILE_TYPE
     , CONTROLFILE_CREATED
     , CONTROLFILE_SEQUENCE#
     , CONTROLFILE_CHANGE#
     , CONTROLFILE_TIME
     , VERSION_TIME
     , PROTECTION_MODE
     , PROTECTION_LEVEL
     , REMOTE_ARCHIVE
     , ACTIVATION#
     , SWITCHOVER#
     , ARCHIVELOG_CHANGE#
     , ARCHIVELOG_COMPRESSION
     , SWITCHOVER_STATUS
     , SUPPLEMENTAL_LOG_DATA_MIN
     , SUPPLEMENTAL_LOG_DATA_PK
     , SUPPLEMENTAL_LOG_DATA_UI
     , FORCE_LOGGING
     , PLATFORM_ID
     , PLATFORM_NAME
     , RECOVERY_TARGET_INCARNATION#
     , LAST_OPEN_INCARNATION#
     , SUPPLEMENTAL_LOG_DATA_FK
     , SUPPLEMENTAL_LOG_DATA_ALL
     , STANDBY_BECAME_PRIMARY_SCN
     , FS_FAILOVER_STATUS
     , FS_FAILOVER_CURRENT_TARGET
     , FS_FAILOVER_THRESHOLD
     , FS_FAILOVER_OBSERVER_PRESENT
     , FS_FAILOVER_OBSERVER_HOST
     , CONTROLFILE_CONVERTED
     , PRIMARY_DB_UNIQUE_NAME
     , SUPPLEMENTAL_LOG_DATA_PL
     , MIN_REQUIRED_CAPTURE_CHANGE#
  FROM GV$DATABASE
/
