set linesize 5000

COL INST_ID FORMAT 99999999999999
COL INSTANCE_NUMBER FORMAT 99999999999999
COL INSTANCE_NAME FORMAT A16
COL HOST_NAME FORMAT A30
COL VERSION FORMAT A17
COL STARTUP_TIME FORMAT A21
COL STATUS FORMAT A12
COL PARALLEL FORMAT A8
COL THREAD# FORMAT 99999999999999
COL ARCHIVER FORMAT A8
COL LOG_SWITCH_WAIT FORMAT A15
COL LOGINS FORMAT A10
COL SHUTDOWN_PENDING FORMAT A16
COL DATABASE_STATUS FORMAT A17
COL INSTANCE_ROLE FORMAT A18
COL ACTIVE_STATE FORMAT A12
COL BLOCKED FORMAT A7

SELECT INST_ID
     , INSTANCE_NUMBER
     , INSTANCE_NAME
     , substr(HOST_NAME, 1, 30) HOST_NAME
     , VERSION
     , STARTUP_TIME
     , STATUS
     , PARALLEL
     , THREAD#
     , ARCHIVER
     , LOG_SWITCH_WAIT
     , LOGINS
     , SHUTDOWN_PENDING
     , DATABASE_STATUS
     , INSTANCE_ROLE
     , ACTIVE_STATE
     , BLOCKED
  FROM GV$INSTANCE
/

@reset