set linesize 2000

COL INST_ID FORMAT 99999999999999
COL ADDR FORMAT A20
COL PID FORMAT 99999999999999
COL SPID FORMAT A24
COL PNAME FORMAT A5
COL USERNAME FORMAT A15
COL SERIAL# FORMAT 99999999999999
COL TERMINAL FORMAT A30
COL PROGRAM FORMAT A48
COL TRACEID FORMAT A255
COL TRACEFILE FORMAT A513
COL BACKGROUND FORMAT A10
COL LATCHWAIT FORMAT A16
COL LATCHSPIN FORMAT A16
COL PGA_USED_MEM FORMAT 99999999999999
COL PGA_ALLOC_MEM FORMAT 99999999999999
COL PGA_FREEABLE_MEM FORMAT 99999999999999
COL PGA_MAX_MEM FORMAT 99999999999999

SELECT P.INST_ID
     , P.ADDR
     , P.PID
     , P.SPID
     , P.PNAME
     , P.USERNAME
     , S.SID
     , P.SERIAL#
     , S.OSUSER
     , S.MACHINE
     , P.TERMINAL
     , P.PROGRAM
	 , S.STATUS
     , P.TRACEID
     , P.TRACEFILE
     , P.BACKGROUND
     , P.LATCHWAIT
     , P.LATCHSPIN
     , P.PGA_USED_MEM
     , P.PGA_ALLOC_MEM
     , P.PGA_FREEABLE_MEM
     , P.PGA_MAX_MEM
  FROM SYS.GV_$PROCESS P
     , SYS.GV_$SESSION S
 WHERE P.ADDR = S.PADDR (+)
-- AND P.SERIAL# = S.SERIAL#
   AND P.INST_ID = S.INST_ID
   AND S.TYPE <> 'BACKGROUND'
   AND S.USERNAME = NVL('&USERNAME', S.USERNAME)
   AND S.STATUS = NVL('&STATUS', S.STATUS)
   AND S.SID = NVL('&SID', S.SID)
 ORDER BY S.USERNAME, S.SID, S.SERIAL#
/