EXECUTE DBMS_LOGMNR.ADD_LOGFILE(logfilename => '+DG_MARTD1_DATA/redo/redo01.log', options => DBMS_LOGMNR.NEW);

-- Outros arquivos
EXECUTE DBMS_LOGMNR.ADD_LOGFILE(logfilename => '/u01/app/oracle/product/10.2.0/db_1/dbs/arch/1_20948_683061300.dbf', options => DBMS_LOGMNR.ADDFILE);

EXECUTE DBMS_LOGMNR.START_LOGMNR(OPTIONS => DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG);

CREATE
  TABLE LOGMNR_CONTENTS AS
SELECT
  * FROM
  V$LOGMNR_CONTENTS;

-- Para finalizar   
EXECUTE DBMS_LOGMNR.END_LOGMNR();







