col "Descrição do LOG" format a80
col rotina format a40
SELECT /*+ index (LOG_PROCESSO_TARIFA IND_LOGPRC_1 )*/
       RPAD(SUBSTR(DS_ROTINA,1,10),10, ' ') "Rotina", RPAD(SUBSTR(DS_LOG,1,75),75, ' ') "Descrição do LOG"
  FROM LOG_PROCESSO_TARIFA
 WHERE TRUNC(TS_ULT_ALZ) = TRUNC(SYSDATE)
   AND DS_ROTINA IN ('LOG', 'FUNC_GTP4105', 'FUNC_GTP4108')
 GROUP BY SUBSTR(DS_ROTINA,1,10), SUBSTR(DS_LOG,1,75), AD_SEQ_LOG
 ORDER BY AD_SEQ_LOG
/
