set lines 300
set pages 3000
set head off
set feedback off

SELECT 'DATABASE '||NAME DATABASE FROM V$DATABASE
/
SELECT TABLESPACE_NAME||' '||
case
    when ALOC_MB < 300  then 'LIM 15'
    when ALOC_MB < 500  then 'LIM 10'
    when ALOC_MB < 1000  then 'LIM 05'
    when ALOC_MB < 5000  then 'LIM 03'
    else 'LIM 02'
end THRESHOLD
FROM
(
SELECT D.TABLESPACE_NAME, SUM(D.BYTES)/1024/1024/1024 ALOC_MB
FROM DBA_DATA_FILES D ,DBA_TABLESPACES T
WHERE D.TABLESPACE_NAME = T.TABLESPACE_NAME
AND   T.CONTENTS NOT IN ('UNDO','TEMPORARY')
GROUP BY D.TABLESPACE_NAME
) ALOC
ORDER BY TABLESPACE_NAME
/
