set linesize 2000

COL GROUP_NUMBER FORMAT 99999999999999
COL DISK_NUMBER FORMAT 99999999999999
COL MOUNT_STATUS FORMAT A12
COL MODE_STATUS FORMAT A11
COL STATE FORMAT A8
COL REDUNDANCY FORMAT A10
COL LIBRARY FORMAT A64
COL TOTAL_MB FORMAT 99999999999999
COL FREE_MB FORMAT 99999999999999
COL NAME FORMAT A30
COL FAILGROUP FORMAT A30
COL PATH FORMAT A256
COL CREATE_DATE FORMAT A21
COL MOUNT_DATE FORMAT A21

SELECT GROUP_NUMBER
     , DISK_NUMBER
     , NAME
     , PATH
     , TOTAL_MB
     , FREE_MB
     , FAILGROUP
     , MODE_STATUS
     , STATE
     , REDUNDANCY
     , MOUNT_STATUS
     , CREATE_DATE
     , MOUNT_DATE
     , LIBRARY
  FROM GV$ASM_DISK
 WHERE GROUP_NUMBER = NVL('&P_GROUP_NUMBER', GROUP_NUMBER)
   AND DISK_NUMBER = NVL('&P_DISK_NUMBER', DISK_NUMBER)
   AND PATH LIKE NVL('&LK_PATH', PATH)
 ORDER BY GROUP_NUMBER, DISK_NUMBER, PATH
/