clear columns
TTITLE OFF
clear buffer computes columns breaks
col NAME_COL_PLUS_SHOW_PARAM format a30
col VALUE_COL_PLUS_SHOW_PARAM format a30
col TYPE format a30
SET ECHO OFF
SET TIMING OFF
SET TAB OFF
SET HEAD ON
SET TERMOUT ON
SET VERIFY OFF
SET LONG 99999
SET FEEDBACK OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
SET FEEDBACK ON
SET LINESIZE 5000
SET PAGESIZE 100
SET SERVEROUT ON SIZE 1000000
SET TIMING ON