set pagesize 999
set linesize 171

COLUMN OWNER FORMAT A15
COLUMN TRIGGER_NAME FORMAT A30
COLUMN TRIGGER_TYPE FORMAT A16
COLUMN TRIGGERING_EVENT FORMAT A20
COLUMN TABLE_OWNER FORMAT A15
COLUMN BASE_OBJECT_TYPE FORMAT A1
COLUMN TABLE_NAME FORMAT A30
COLUMN WHEN_CLAUSE FORMAT A20
COLUMN STATUS FORMAT A8

SELECT OWNER
     , TRIGGER_NAME
     , TRIGGER_TYPE
     , substr(TRIGGERING_EVENT, 1, 20) TRIGGERING_EVENT
     , TABLE_OWNER
     , decode(BASE_OBJECT_TYPE, 'TABLE', 'T', 'DATABASE', 'D') BASE_OBJECT_TYPE
     , TABLE_NAME
     , substr(WHEN_CLAUSE, 1, 20) WHEN_CLAUSE
     , STATUS
  FROM DBA_TRIGGERS
 WHERE TABLE_OWNER like NVL('&TABOWNER', TABLE_OWNER)
   AND (   (TABLE_NAME like NVL('&TABNAME', TABLE_NAME) AND TABLE_NAME IS NOT NULL)
         OR TABLE_NAME IS NULL
       )
   AND TRIGGER_NAME like NVL('&TRIGGERNAME', TRIGGER_NAME)
/
