SET ECHO      OFF;
SET FEEDBACK  OFF;
SET VERIFY    OFF;
SET PAGESIZE  0;
SET TERMOUT   ON;
SET HEADING   OFF;
SET TRIMSPOOL ON;
spool tablespaces_monitored_1.txt

SELECT TABLESPACE_NAME || ' LIM ' ||
CASE
    when GIGAS < 101  then '15'
    when GIGAS < 501  then '10'
    else '5'
END 
FROM
(
SELECT D.TABLESPACE_NAME, SUM(D.BYTES)/1024/1024/1024 GIGAS
FROM DBA_DATA_FILES D ,DBA_TABLESPACES T
WHERE D.TABLESPACE_NAME = T.TABLESPACE_NAME
AND   T.CONTENTS NOT IN ('UNDO','TEMPORARY')
GROUP BY D.TABLESPACE_NAME
)
ORDER BY TABLESPACE_NAME
/
spool off;
clear columns
clear computes
SET PAGESIZE  50;
SET HEADING   ON;