@reset

break on DB_NAME skip page

COL GROUP_NUMBER FORMAT 99999
COL INSTANCE_NAME FORMAT A30
COL DB_NAME FORMAT A8
COL STATUS FORMAT A12
COL SOFT_VERSION FORMAT A12
COL COMPATIBLE_V FORMAT A12

SELECT DB_NAME
     , GROUP_NUMBER
     , INSTANCE_NAME
     , STATUS
     , SOFTWARE_VERSION SOFT_VERSION
     , COMPATIBLE_VERSION COMPATIBLE_V
  FROM V$ASM_CLIENT
 ORDER BY DB_NAME, INSTANCE_NAME, GROUP_NUMBER, STATUS
/
