col owner for a20
col MVIEW_NAME for a20
col QUERY for a70

select OWNER,MVIEW_NAME,QUERY,UPDATABLE,UPDATE_LOG,BUILD_MODE,LAST_REFRESH_DATE,LAST_REFRESH_TYPE from DBA_MVIEWS where MVIEW_NAME='&mview_name';