
PROMPT 'COUNT DE STATUS ÍNDICES NÃO PARTICIONADOS'
SELECT STATUS, COUNT(1) TOTAL FROM DBA_INDEXES group by  STATUS;

PROMPT 'COUNT DE STATUS ÍNDICES PARTICIONADOS' 
SELECT STATUS, COUNT(1) TOTAL FROM DBA_IND_PARTITIONS group by  STATUS;


PROMPT 'COUNT DE STATUS ÍNDICES SUBPARTICIONADOS'
SELECT STATUS, COUNT(1) TOTAL FROM DBA_IND_SUBPARTITIONS group by  STATUS;



PROMPT 'ÍNDICES NÃO PARTICIONADOS - status unusable'
SELECT owner, index_name, STATUS FROM DBA_INDEXES where STATUS ='UNUSABLE';

PROMPT 'COUNT DE STATUS ÍNDICES PARTICIONADOS' 
SELECT INDEX_owner, index_name, PARTITION_NAME, STATUS FROM DBA_IND_PARTITIONS  where STATUS ='UNUSABLE';


